server:
  port: 2222
spring:
  application:
    name: server-call-history
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.2.227:3306/vicmob_xyh?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: admin
    password: lJAT6u9HH8QWAMGDjA

    initialSize: 1  #初始化大小
    minIdle: 1  #空闲连接池的大小
    maxActive: 50 #最大激活数量
#MyBatis配置文件
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
# eureka:
#   client:
#     service-url:
#       defaultZone: http://127.0.0.1:1111/eureka/
swagger:
  enable: true #是否开启swagger
#日志打印SQL
logging:
  level:
    com.vicmob: debug  #日志级别
  config: classpath:logback-dev.xml  #加载指定日志文件
